name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49a0f064300c34711014f970726dad17852db1c16a3dd2f5e4dca8c0ebf7b02a"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
