name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e61da4ed2c26b265c348d9e13f7818f75d9320cb96f75efcfd5d386b6e65cd9"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
