name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fffc5d2653446ea1ed13d10a866b4e7f76c7412727e46afefea825a6cb1c8c0a"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
