name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b301896213657148f79b35963e83d1a664c439c65620bfa9583a14be346b1aa2"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
