name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e6ffe754797959bc870df9935f842dffe7f0e7518c2c1ebda2b6be956668e76"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
