name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beaad039de592963d3d656947aa5054e1977a714ae93eea473846cf06ee69d16"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
