name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eee891988c54d77f221f5d483ecbbcf886e8bd137f8e6a9127dcec2ac60b729"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
