name = "Tree of Life"
author = "JRcrhd & HeCUan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65905d210ab07af3e9cb35cd7fdf0e104afecbbe35d552dec2a76bab7e9eb3cf"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"
